### ISSUE TITLE
Publish package

### ISSUE THREAD

**Issue by ctron** [secvisogram/csaf-validator-lib#152]
In order to more easily consume this functionality, it would be great if that could be published to npmjs.org

**Comment by tschmidtb51** [comment]
Actually, we already do that: https://www.npmjs.com/package/@secvisogram/csaf-validator-lib

**Comment by tschmidtb51** [comment]
Is there something that we should improve?

**Comment by tschmidtb51** [comment]
We need to change the documentation so that it is:
- [ ] pointing to the npm package
- [ ] keep the `git subtree` instruction as alternative way (as a separate section, e.g. "advanced")

**Comment by ctron** [comment]
> I just saw that we still write in the README, that there is no npm package - time to change that...

Yes, that was the reason for me opening this. I didn't even check npmjs.org because of that.

So, that one should be easy to fix :grinning:
