### ISSUE TITLE
Invalid CPE regular expression

### ISSUE THREAD

**Issue by ctron** [secvisogram/csaf-validator-lib#156]
Running the validation for `csaf_2_0` and `csaf_2_0_strict`, I get the following error:

```
"csaf_2_0: must match pattern \"^(cpe:2\\.3:[aho\\*\\-](:(((\\?*|\\*?)([a-zA-Z0-9\\-\\._]|(\\\\[\\\\\\*\\?!\"#\\$%&'\\(\\)\\+,/:;<=>@\\[\\]\\^`\\{\\|\\}~]))+(\\?*|\\*?))|[\\*\\-])){5}(:(([a-zA-Z]{2,3}(-([a-zA-Z]{2}|[0-9]{3}))?)|[\\*\\-]))(:(((\\?*|\\*?)([a-zA-Z0-9\\-\\._]|(\\\\[\\\\\\*\\?!\"#\\$%&'\\(\\)\\+,/:;<=>@\\[\\]\\^`\\{\\|\\}~]))+(\\?*|\\*?))|[\\*\\-])){4})|([c][pP][eE]:/[AHOaho]?(:[A-Za-z0-9\\._\\-~%]*){0,6})$\"", "csaf_2_0_strict: must match pattern \"^(cpe:2\\.3:[aho\\*\\-](:(((\\?*|\\*?)([a-zA-Z0-9\\-\\._]|(\\\\[\\\\\\*\\?!\"#\\$%&'\\(\\)\\+,/:;<=>@\\[\\]\\^`\\{\\|\\}~]))+(\\?*|\\*?))|[\\*\\-])){5}(:(([a-zA-Z]{2,3}(-([a-zA-Z]{2}|[0-9]{3}))?)|[\\*\\-]))(:(((\\?*|\\*?)([a-zA-Z0-9\\-\\._]|(\\\\[\\\\\\*\\?!\"#\\$%&'\\(\\)\\+,/:;<=>@\\[\\]\\^`\\{\\|\\}~]))+(\\?*|\\*?))|[\\*\\-])){4})|([c][pP][eE]:/[AHOaho]?(:[A-Za-z0-9\\._\\-~%]*){0,6})$\""
```

Testing again the following CPE: `cpe:/o:redhat:enterprise_linux:8::fastdatapath` (which seems valid to me).

Testing with another regular expression too, I get an error that the regular expression is invalid for ECMAScript. Caused by two missing escape backslashes:

Diff:

```diff
- ^(cpe:2\.3:[aho\*\-](:(((\?*|\*?)([a-zA-Z0-9\-\._]|(\\[\\\*\?!"#\$%&'\(\)\+,/:;<=>@\[\]\^`\{\|\}~]))+(\?*|\*?))|[\*\-])){5}(:(([a-zA-Z]{2,3}(-([a-zA-Z]{2}|[0-9]{3}))?)|[\*\-]))(:(((\?*|\*?)([a-zA-Z0-9\-\._]|(\\[\\\*\?!"#\$%&'\(\)\+,/:;<=>@\[\]\^`\{\|\}~]))+(\?*|\*?))|[\*\-])){4})|([c][pP][eE]:/[AHOaho]?(:[A-Za-z0-9\._\-~%]*){0,6})$"", "csaf_2_0_strict: must match pattern "^(cpe:2\.3:[aho\*\-](:(((\?*|\*?)([a-zA-Z0-9\-\._]|(\\[\\\*\?!"#\$%&'\(\)\+,/:;<=>@\[\]\^`\{\|\}~]))+(\?*|\*?))|[\*\-])){5}(:(([a-zA-Z]{2,3}(-([a-zA-Z]{2}|[0-9]{3}))?)|[\*\-]))(:(((\?*|\*?)([a-zA-Z0-9\-\._]|(\\[\\\*\?!"#\$%&'\(\)\+,/:;<=>@\[\]\^`\{\|\}~]))+(\?*|\*?))|[\*\-])){4})|([c][pP][eE]:/[AHOaho]?(:[A-Za-z0-9\._\-~%]*){0,6})$
+ ^(cpe:2\.3:[aho\*\-](:(((\?*|\*?)([a-zA-Z0-9\-\._]|(\\[\\\*\?!"#\$%&'\(\)\+,/:;<=>@\[\]\^`\{\|\}~]))+(\?*|\*?))|[\*\-])){5}(:(([a-zA-Z]{2,3}(-([a-zA-Z]{2}|[0-9]{3}))?)|[\*\-]))(:(((\?*|\*?)([a-zA-Z0-9\-\._]|(\\[\\\*\?!"#\$%&'\(\)\+,/:;<=>@\[\]\^`\{\|\}~]))+(\?*|\*?))|[\*\-])){4})|([c][pP][eE]:\/[AHOaho]?(:[A-Za-z0-9\._\-~%]*){0,6})$"", "csaf_2_0_strict: must match pattern "^(cpe:2\.3:[aho\*\-](:(((\?*|\*?)([a-zA-Z0-9\-\._]|(\\[\\\*\?!"#\$%&'\(\)\+,/:;<=>@\[\]\^`\{\|\}~]))+(\?*|\*?))|[\*\-])){5}(:(([a-zA-Z]{2,3}(-([a-zA-Z]{2}|[0-9]{3}))?)|[\*\-]))(:(((\?*|\*?)([a-zA-Z0-9\-\._]|(\\[\\\*\?!"#\$%&'\(\)\+,/:;<=>@\[\]\^`\{\|\}~]))+(\?*|\*?))|[\*\-])){4})|([c][pP][eE]:\/[AHOaho]?(:[A-Za-z0-9\._\-~%]*){0,6})$
```

![image](https://github.com/secvisogram/csaf-validator-service/assets/202474/93e450c0-9031-434b-aef0-5e4a0f742934)

**Comment by tschmidtb51** [comment]
Hmm, interesting... I have to investigate that... That case did not occur in the CPE dictionary...

**Comment by ctron** [comment]
Maybe it depends on the regular expression implementation. But escaping the `/` seemed reasonable to me.

**Comment by tschmidtb51** [comment]
I was just wondering: Is that a problem of the standard (as the pattern does not escape any `/`) or just an issue of the implementation?

**Comment by ctron** [comment]
I am not sure where the csaf-validator-lib gets the regexp from.

**Comment by tschmidtb51** [comment]
Note to self: According to the [test script](https://github.com/oasis-tcs/csaf/blob/master/csaf_2.0/test/cpe/run_tests.sh) the JSON schema patter is correct an validates also `cpe:/o:redhat:enterprise_linux:8::fastdatapath` :relieved:

**Comment by tschmidtb51** [comment]
So the error must have been introduced while converting the regex from JSON to Javascript...

**Comment by tschmidtb51** [comment]
It might actually be implementation specific as I don't get the error when using Secvisogram. So, I wonder whether this repo is the correct place to fix it.

**Comment by ctron** [comment]
Ok, let me try dig a bit into that and find out more.

**Comment by tschmidtb51** [comment]
> Ok, let me try dig a bit into that and find out more.

Thank you.

The key question for me would be: Is it allowed to omit the escaping for `/` in JSON. If not => CSAF standard must fix that. If yes, probably an implementation issue (as it works with `nodejs`).

**Comment by ctron** [comment]
Ok, so there's definitely something wrong with the whole regexp stuff, playing with that same regexp on the console of `deno` (works the same way with `bun` and `node`):

![image](https://github.com/secvisogram/csaf-validator-lib/assets/202474/795454ce-23dc-407a-83cd-16f304039a46)

It accepts `XXcpe:/o:redhat:rhel_aus:7.6::server` as a valid CPE.

**Comment by ctron** [comment]
Which is btw the same behavior I see changing a CPE in the tests of `csaf-validator-lib`.

**Comment by ctron** [comment]
Regexps still give me a headache, still I think I understand why that is:

![image](https://github.com/secvisogram/csaf-validator-lib/assets/202474/94c81bdd-f6bd-48da-bbc5-85ea14696a5c)

The regexp is kind of like: `^(a)|(b)$` … where it should be: `^(a|b)$`.

Still, that's an additional problem, and not the one that I run into.

**Comment by tschmidtb51** [comment]
@ctron Could you please confirm: You are using that this library via `deno`?

**Comment by ctron** [comment]
> @ctron Could you please confirm: You are using that this library via `deno`?

Embedding this (the problem with the missing slashes) comes from an embedded deno use case. However, there's a second component to it: `rollup`. Testing with `bun`, `node`, `deno` in general leads to the same results. While I can't really reproduce it so far, my gut feeling is that this is being caused for using `rollup` to create the file I embed in the Rust code.

Nevertheless, the regexp still allows for values such as `ABCcpe:/…` on all environments, simpley as the regexp is wrong.

**Comment by tschmidtb51** [comment]
> Nevertheless, the regexp still allows for values such as `ABCcpe:/…` on all environments, simpley as the regexp is wrong.

True and accepted. This is tracked in https://github.com/oasis-tcs/csaf/issues/693 It's up to the TC to decide, what the solution will be, please stay tuned.

**Comment by tschmidtb51** [comment]
After reading the spec, I'm still confused what the correct answer regarding the `/` escaping might be, so I opened the discussion to the JSON spec authors: https://github.com/orgs/json-schema-org/discussions/684
Feel free to upvote.

**Comment by tschmidtb51** [comment]
> > Nevertheless, the regexp still allows for values such as `ABCcpe:/…` on all environments, simpley as the regexp is wrong.
> 
> True and accepted. This is tracked in [oasis-tcs/csaf#693](https://github.com/oasis-tcs/csaf/issues/693) It's up to the TC to decide, what the solution will be, please stay tuned.

The change is now part of the [current Editor Revision for CSAF 2.1](https://github.com/oasis-tcs/csaf/pull/714).

**Comment by tschmidtb51** [comment]
> After reading the spec, I'm still confused what the correct answer regarding the `/` escaping might be, so I opened the discussion to the JSON spec authors: https://github.com/orgs/json-schema-org/discussions/684 Feel free to upvote.

BTW: I also started to investigate different implementations at: https://github.com/tschmidtb51/JSON-schema-pattern
Feel free to contribute.

The Node one is more or less what I would expect...

**Comment by tschmidtb51** [comment]
I still think that the `/` issue is not our bug - but the TC decided to quote it in CSAF 2.1 and [allow backports without loosing  conformance](https://github.com/oasis-tcs/csaf/blob/master/csaf_2.0/guidance/faq.md#the-cpe-pattern-changed-from-csaf-20-to-csaf-21-why).
