### ISSUE TITLE
Validation of document.version and revsion.number

### ISSUE THREAD

**Issue by mfd2007** [secvisogram/csaf-validator-lib#67]
If a document contains a pre-release-version (like 1.0.1-1.0) in `document.version` and a matching `revision_history` entry with the same content in `revision_history[].number`, there are two warnings:
`revision_history[].number` -> contains prerelease part
`document.version` -> version does not match latest revision

`{
  "document": {
    "category": "csaf_base",
    "csaf_version": "2.0",
    "publisher": {
      "category": "discoverer",
      "name": "test",
      "namespace": "http://example.test"
    },
    "title": "test_1",
    "tracking": {
      "current_release_date": "2022-01-01T00:00:00.000Z",
      "id": "111",
      "initial_release_date": "2022-01-01T00:00:00.000Z",
      "revision_history": [
        {
          "date": "2022-01-01T00:00:00.000Z",
          "number": "1.0.0",
          "summary": "\"Initial Publication\""
        },
        {
          "date": "2022-01-01T00:00:00.001Z",
          "number": "1.0.1-1.0",
          "summary": "New Version"
        }
      ],
      "status": "draft",
      "version": "1.0.1-1.0"
    }
  }
}`

Maybe the check according the matching according the latest version with a pre-release-tag could be done against the latest revision history entry?

**Comment by cloeser** [comment]
We have noticed the error "version does not match latest revision" as well and this is a bug in test 6.1.16. We are already working on that and a fix should be released soon.

The error "contains prerelease part" is from test 6.1.19 and is working as specified. A Revision History element must not contain a pre-release part. (I have added this to the agenda of our meeting today for further discussion.)
